name: Titan Ultimate Build
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Build Tools
        run: |
          sudo apt update
          sudo apt install -y build-essential libffi-dev libssl-dev libsqlite3-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 kivy

      - name: Build with Buildozer
        run: |
          # Is command se saari licenses khud accept ho jayengi
          yes | buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "True"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Titan-AI-Full-Options
          path: bin/*.apk
